name: hello world
on: 
  push:
    branches: [main]
jobs: 
  say-hello:
    runs-on: ubuntu-latest
    name: test
    steps: 
      - name: set day
        run: echo "ToDay=$(date +%y-%m-%d)" >> $GITHUB_ENV
      - name: today
        run: echo "hello world, today is  ${{env.ToDay}}"
