name: hello world
on: 
  push:
    branches: [main]
jobs: 
  say-hello:
    runs-on: ubuntu-latest
    name: test
    steps: 
      - run: echo "ToDay = $(date + %y-%m-%d)" >> $GITHUB_ENV
      - run: echo hello world
      - run: echo today is $ToDay
