name: workflow
on: 
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *'
jobs: 
  schedule_for_github_action:
    runs-on: ubuntu-latest
    name: test_schedule
    steps: 
      - name: checkout
        uses: actions/checkout@v3
        
      - name: unit test
        run: |
          python test/test_extractor.py
          
      - name: get_time
        run: echo "The current time is $(date)"
