name: workflow
on: 
  push:
    branches: [main]
jobs: 
  schedule_for_github_action:
    runs-on: ubuntu-latest
    name: test_schedule
    steps: 
      - name: unit test
        run: test/test_extractor.py
      - name: get_time
        run: echo "The current time is $(date)"
